package com.TaskVantibolli.hbm;
// default package
// Generated Dec 31, 2017 10:12:37 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name = "brands")
public class Brands implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long brandId;
	@Column
	private Companies companies;
	@Column
	private String brandName;
	@Column
	private String brandDescp;
	
	
	public Brands() {
	}

	public Brands(Companies companies, String brandName, String brandDescp, Set productses) {
		this.companies = companies;
		this.brandName = brandName;
		this.brandDescp = brandDescp;
		
	}



	public long getBrandId() {
		return brandId;
	}

	public void setBrandId(long brandId) {
		this.brandId = brandId;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getBrandDescp() {
		return this.brandDescp;
	}

	public void setBrandDescp(String brandDescp) {
		this.brandDescp = brandDescp;
	}

	
}
