package com.TaskVantibolli.hbm;
// default package
// Generated Dec 31, 2017 10:12:37 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Companies generated by hbm2java
 */
public class Companies implements java.io.Serializable {

	private long compId;
	private String companyName;
	private String companySpec;
	private String companyDescription;
	

	public Companies() {
	}

	public Companies(String companyName, String companySpec, String companyDescription, Set brandses) {
		this.companyName = companyName;
		this.companySpec = companySpec;
		this.companyDescription = companyDescription;
		
	}



	public long getCompId() {
		return compId;
	}

	public void setCompId(long compId) {
		this.compId = compId;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanySpec() {
		return this.companySpec;
	}

	public void setCompanySpec(String companySpec) {
		this.companySpec = companySpec;
	}

	public String getCompanyDescription() {
		return this.companyDescription;
	}

	public void setCompanyDescription(String companyDescription) {
		this.companyDescription = companyDescription;
	}

	
}
