package com.TaskVantibolli.hbm;
// default package
// Generated Dec 31, 2017 10:12:37 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Offices generated by hbm2java
 */
public class Offices implements java.io.Serializable {

	private Integer officeId;
	private String officeName;
	private String officeLocation;
	private Set warehouses = new HashSet(0);

	public Offices() {
	}

	public Offices(String officeName, String officeLocation, Set warehouses) {
		this.officeName = officeName;
		this.officeLocation = officeLocation;
		this.warehouses = warehouses;
	}

	public Integer getOfficeId() {
		return this.officeId;
	}

	public void setOfficeId(Integer officeId) {
		this.officeId = officeId;
	}

	public String getOfficeName() {
		return this.officeName;
	}

	public void setOfficeName(String officeName) {
		this.officeName = officeName;
	}

	public String getOfficeLocation() {
		return this.officeLocation;
	}

	public void setOfficeLocation(String officeLocation) {
		this.officeLocation = officeLocation;
	}

	public Set getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Set warehouses) {
		this.warehouses = warehouses;
	}

}
