package com.TaskVantibolli.hbm;
// default package
// Generated Dec 31, 2017 10:12:37 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producttypes generated by hbm2java
 */
@Entity
@Table(name = "producttypes")
public class Producttypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long prodTypeId;
	@Column
	private String prodTypeName;
	@Column
	private String prodTypeDetails;

	

	public Producttypes() {
	}

	public Producttypes(String prodTypeName, String prodTypeDetails, Set productses) {
		this.prodTypeName = prodTypeName;
		this.prodTypeDetails = prodTypeDetails;
		
	}



	public long getProdTypeId() {
		return prodTypeId;
	}

	public void setProdTypeId(long prodTypeId) {
		this.prodTypeId = prodTypeId;
	}

	public String getProdTypeName() {
		return this.prodTypeName;
	}

	public void setProdTypeName(String prodTypeName) {
		this.prodTypeName = prodTypeName;
	}

	public String getProdTypeDetails() {
		return this.prodTypeDetails;
	}

	public void setProdTypeDetails(String prodTypeDetails) {
		this.prodTypeDetails = prodTypeDetails;
	}

}
