package com.TaskVantibolli.hbm;
// default package
// Generated Dec 31, 2017 10:12:37 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products")
public class Products implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column
	@GeneratedValue(strategy=GenerationType.AUTO)
	private String prodId;
	@Column
	private Brands brands;
	@Column
	private Producttypes producttypes;
	@Column
	private String prodDescription;
	@Column
	private String prodMvalue;
	@Column
	private String prodSize;
	
	

	public Products() {
	}

	public Products(Brands brands, Producttypes producttypes, String prodDescription, String prodMvalue,
			String prodSize) {
		this.brands = brands;
		this.producttypes = producttypes;
		this.prodDescription = prodDescription;
		this.prodMvalue = prodMvalue;
		this.prodSize = prodSize;
	
	}

	

	



	

	public String getProdId() {
		return prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	public Producttypes getProducttypes() {
		return this.producttypes;
	}

	public void setProducttypes(Producttypes producttypes) {
		this.producttypes = producttypes;
	}

	public String getProdDescription() {
		return this.prodDescription;
	}

	public void setProdDescription(String prodDescription) {
		this.prodDescription = prodDescription;
	}

	public String getProdMvalue() {
		return this.prodMvalue;
	}

	public void setProdMvalue(String prodMvalue) {
		this.prodMvalue = prodMvalue;
	}

	public String getProdSize() {
		return this.prodSize;
	}

	public void setProdSize(String prodSize) {
		this.prodSize = prodSize;
	}

	
}
