package com.TaskVantibolli.hbm;
// default package
// Generated Dec 31, 2017 10:12:37 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name = "warehouse")
public class Warehouse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column
	@GeneratedValue(strategy=GenerationType.AUTO)
	private String warehouseId;
	@Column
	private Offices offices;
	@Column
	private Products products;
	@Column
	private String inStock;
	@Column
	private String avlQty;
	@Column
	private String inTransit;
	@Column
	private String moq;
	@Column
	private String qpb;
	@Column
	private String reorderPoint;
	@Column
	private String warehouseDescp;

	public Warehouse() {
	}

	public Warehouse(Offices offices, Products products, String inStock, String avlQty, String inTransit, String moq,
			String qpb, String reorderPoint, String warehouseDescp) {
		this.offices = offices;
		this.products = products;
		this.inStock = inStock;
		this.avlQty = avlQty;
		this.inTransit = inTransit;
		this.moq = moq;
		this.qpb = qpb;
		this.reorderPoint = reorderPoint;
		this.warehouseDescp = warehouseDescp;
	}

	

	public String getWarehouseId() {
		return warehouseId;
	}

	public void setWarehouseId(String warehouseId) {
		this.warehouseId = warehouseId;
	}

	public Offices getOffices() {
		return this.offices;
	}

	public void setOffices(Offices offices) {
		this.offices = offices;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public String getInStock() {
		return this.inStock;
	}

	public void setInStock(String inStock) {
		this.inStock = inStock;
	}

	public String getAvlQty() {
		return this.avlQty;
	}

	public void setAvlQty(String avlQty) {
		this.avlQty = avlQty;
	}

	public String getInTransit() {
		return this.inTransit;
	}

	public void setInTransit(String inTransit) {
		this.inTransit = inTransit;
	}

	public String getMoq() {
		return this.moq;
	}

	public void setMoq(String moq) {
		this.moq = moq;
	}

	public String getQpb() {
		return this.qpb;
	}

	public void setQpb(String qpb) {
		this.qpb = qpb;
	}

	public String getReorderPoint() {
		return this.reorderPoint;
	}

	public void setReorderPoint(String reorderPoint) {
		this.reorderPoint = reorderPoint;
	}

	public String getWarehouseDescp() {
		return this.warehouseDescp;
	}

	public void setWarehouseDescp(String warehouseDescp) {
		this.warehouseDescp = warehouseDescp;
	}

}
